spring.security.user.name=abc
spring.security.user.password=1234

spring.servlet.session.cookie.same-side=strict

spring.datasource.url=jdbc:postgresql://localhost:5432/SpringBoot_Demo
spring.datasource.username=postgres
spring.datasource.password=root
